@startuml frontend

사용자 --|> "시작 페이지" : 입력
"시작 페이지" : "번역문 입력"

"시작 페이지" --|> "출력 조건"
"출력 조건" : "출력 조건 부합 여부"
"출력 조건" : "조건(Y/N)"

"출력 조건" --|> "토큰" : YES
"출력 조건" --|> "시작 페이지" : NO

토큰 --|> "결과값 출력" : YES
토큰 --|> "수정/삭제" : NO
토큰 : "Yes"

토큰 : "No"

"결과값 출력" --|> "서버에 저장"
"수정/삭제" --|> "서버에 저장"
@enduml